# data
dataset: 'CVC'
root: './datasets/cvc612/'
train_data_dir: 'train'
valid_data_dir: 'val'
test_data_dir: 'cvc612'

# train
model: 'PraNet'
loss: 'TotalStructureLoss'
trainsize : 352
nEpoch: 200
batch_size: 32
num_workers: 8
use_gpu: True
lr: 0.001
weight_decay: 0.00001
mt: 0.9
power: 0.9
nclasses: 1
multiscale: True
size_rates: [0.75, 1.25, 1]
clip_gradient: True
clip: 0.5

# validation & test
val_period: 0  # 0 for disable validation
testsize : 352

