# data
dataset: 'CVC'
root: './datasets/cvc612/'
train_data_dir: 'train'
valid_data_dir: 'val'
test_data_dir: 'CVC-300'
trainsize: 352

# train
nEpoch: 200
batch_size: 16
num_workers: 8
use_gpu: True
model: 'UNet'
loss: 'BceDiceLoss'
lr: 0.001
weight_decay: 0.00001
mt: 0.9
power: 0.9
nclasses: 1
multiscale: False
clip_gradient: False

# validation & test
val_period: 0  # 0 for disable validation
testsize : 352
